### ISSUE TITLE
Please update for latest verison of RuneLite

### ISSUE THREAD

**Issue by FakeMayo** [gazivodag/runedoku#2]
The Runedoku plugin has disappeared from the RuneLite Plugin Hub following the most recent update. I leaned on this plugin heavily to source cosmic runes for my low level iron for some time now. If anyone is still monitoring this repo, please _please_ update for the most recent RuneLite. Thanks so much to anyone that may see this message.

**Comment by nilPadisha** [comment]
Would also appreciate if it if this was done

**Comment by FakeMayo** [comment]
Plugin is now working on RL. Not sure the fix, but this issue is no longer valid.
